#!/usr/bin/env bash

MSYS_NO_PATHCONV=1 \  # this is to avoid path conversion on Windows Git Bash
docker run -it --rm \
    -v $(pwd):/minidocker \
    -w /minidocker \
    -e PYTHONPATH=/minidocker/src \
    minidocker:dev bash

